/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: galaxy.common.protocols.peer_common.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "galaxy.common.protocols.peer_common.pb-c.h"
void   galaxy__common__protocols__peer_common__property__init
                     (Galaxy__Common__Protocols__PeerCommon__Property         *message)
{
  static const Galaxy__Common__Protocols__PeerCommon__Property init_value = GALAXY__COMMON__PROTOCOLS__PEER_COMMON__PROPERTY__INIT;
  *message = init_value;
}
size_t galaxy__common__protocols__peer_common__property__get_packed_size
                     (const Galaxy__Common__Protocols__PeerCommon__Property *message)
{
  assert(message->base.descriptor == &galaxy__common__protocols__peer_common__property__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t galaxy__common__protocols__peer_common__property__pack
                     (const Galaxy__Common__Protocols__PeerCommon__Property *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &galaxy__common__protocols__peer_common__property__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t galaxy__common__protocols__peer_common__property__pack_to_buffer
                     (const Galaxy__Common__Protocols__PeerCommon__Property *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &galaxy__common__protocols__peer_common__property__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Galaxy__Common__Protocols__PeerCommon__Property *
       galaxy__common__protocols__peer_common__property__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Galaxy__Common__Protocols__PeerCommon__Property *)
     protobuf_c_message_unpack (&galaxy__common__protocols__peer_common__property__descriptor,
                                allocator, len, data);
}
void   galaxy__common__protocols__peer_common__property__free_unpacked
                     (Galaxy__Common__Protocols__PeerCommon__Property *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &galaxy__common__protocols__peer_common__property__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor galaxy__common__protocols__peer_common__property__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Galaxy__Common__Protocols__PeerCommon__Property, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Galaxy__Common__Protocols__PeerCommon__Property, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned galaxy__common__protocols__peer_common__property__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange galaxy__common__protocols__peer_common__property__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor galaxy__common__protocols__peer_common__property__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "galaxy.common.protocols.peer_common.Property",
  "Property",
  "Galaxy__Common__Protocols__PeerCommon__Property",
  "galaxy.common.protocols.peer_common",
  sizeof(Galaxy__Common__Protocols__PeerCommon__Property),
  2,
  galaxy__common__protocols__peer_common__property__field_descriptors,
  galaxy__common__protocols__peer_common__property__field_indices_by_name,
  1,  galaxy__common__protocols__peer_common__property__number_ranges,
  (ProtobufCMessageInit) galaxy__common__protocols__peer_common__property__init,
  NULL,NULL,NULL    /* reserved[123] */
};
