/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: galaxy.common.protocols.connection.proto */

#ifndef PROTOBUF_C_galaxy_2ecommon_2eprotocols_2econnection_2eproto__INCLUDED
#define PROTOBUF_C_galaxy_2ecommon_2eprotocols_2econnection_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Galaxy__Common__Protocols__Connection__Ping Galaxy__Common__Protocols__Connection__Ping;
typedef struct Galaxy__Common__Protocols__Connection__Pong Galaxy__Common__Protocols__Connection__Pong;


/* --- enums --- */

typedef enum _Galaxy__Common__Protocols__Connection__MessageType {
  GALAXY__COMMON__PROTOCOLS__CONNECTION__MESSAGE_TYPE__UNKNOWN_MESSAGE = 0,
  GALAXY__COMMON__PROTOCOLS__CONNECTION__MESSAGE_TYPE__PING = 1,
  GALAXY__COMMON__PROTOCOLS__CONNECTION__MESSAGE_TYPE__PONG = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GALAXY__COMMON__PROTOCOLS__CONNECTION__MESSAGE_TYPE)
} Galaxy__Common__Protocols__Connection__MessageType;

/* --- messages --- */

struct  Galaxy__Common__Protocols__Connection__Ping
{
  ProtobufCMessage base;
  protobuf_c_boolean has_ping_time;
  uint32_t ping_time;
};
#define GALAXY__COMMON__PROTOCOLS__CONNECTION__PING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&galaxy__common__protocols__connection__ping__descriptor) \
, 0, 0 }


struct  Galaxy__Common__Protocols__Connection__Pong
{
  ProtobufCMessage base;
  protobuf_c_boolean has_ping_time;
  uint32_t ping_time;
};
#define GALAXY__COMMON__PROTOCOLS__CONNECTION__PONG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&galaxy__common__protocols__connection__pong__descriptor) \
, 0, 0 }


/* Galaxy__Common__Protocols__Connection__Ping methods */
void   galaxy__common__protocols__connection__ping__init
                     (Galaxy__Common__Protocols__Connection__Ping         *message);
size_t galaxy__common__protocols__connection__ping__get_packed_size
                     (const Galaxy__Common__Protocols__Connection__Ping   *message);
size_t galaxy__common__protocols__connection__ping__pack
                     (const Galaxy__Common__Protocols__Connection__Ping   *message,
                      uint8_t             *out);
size_t galaxy__common__protocols__connection__ping__pack_to_buffer
                     (const Galaxy__Common__Protocols__Connection__Ping   *message,
                      ProtobufCBuffer     *buffer);
Galaxy__Common__Protocols__Connection__Ping *
       galaxy__common__protocols__connection__ping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   galaxy__common__protocols__connection__ping__free_unpacked
                     (Galaxy__Common__Protocols__Connection__Ping *message,
                      ProtobufCAllocator *allocator);
/* Galaxy__Common__Protocols__Connection__Pong methods */
void   galaxy__common__protocols__connection__pong__init
                     (Galaxy__Common__Protocols__Connection__Pong         *message);
size_t galaxy__common__protocols__connection__pong__get_packed_size
                     (const Galaxy__Common__Protocols__Connection__Pong   *message);
size_t galaxy__common__protocols__connection__pong__pack
                     (const Galaxy__Common__Protocols__Connection__Pong   *message,
                      uint8_t             *out);
size_t galaxy__common__protocols__connection__pong__pack_to_buffer
                     (const Galaxy__Common__Protocols__Connection__Pong   *message,
                      ProtobufCBuffer     *buffer);
Galaxy__Common__Protocols__Connection__Pong *
       galaxy__common__protocols__connection__pong__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   galaxy__common__protocols__connection__pong__free_unpacked
                     (Galaxy__Common__Protocols__Connection__Pong *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Galaxy__Common__Protocols__Connection__Ping_Closure)
                 (const Galaxy__Common__Protocols__Connection__Ping *message,
                  void *closure_data);
typedef void (*Galaxy__Common__Protocols__Connection__Pong_Closure)
                 (const Galaxy__Common__Protocols__Connection__Pong *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    galaxy__common__protocols__connection__message_type__descriptor;
extern const ProtobufCMessageDescriptor galaxy__common__protocols__connection__ping__descriptor;
extern const ProtobufCMessageDescriptor galaxy__common__protocols__connection__pong__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_galaxy_2ecommon_2eprotocols_2econnection_2eproto__INCLUDED */
