/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: galaxy.common.protocols.peer_to_peer.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "galaxy.common.protocols.peer_to_peer.pb-c.h"
void   galaxy__common__protocols__peer_to_peer__lobby_properties_notification__init
                     (Galaxy__Common__Protocols__PeerToPeer__LobbyPropertiesNotification         *message)
{
  static const Galaxy__Common__Protocols__PeerToPeer__LobbyPropertiesNotification init_value = GALAXY__COMMON__PROTOCOLS__PEER_TO_PEER__LOBBY_PROPERTIES_NOTIFICATION__INIT;
  *message = init_value;
}
size_t galaxy__common__protocols__peer_to_peer__lobby_properties_notification__get_packed_size
                     (const Galaxy__Common__Protocols__PeerToPeer__LobbyPropertiesNotification *message)
{
  assert(message->base.descriptor == &galaxy__common__protocols__peer_to_peer__lobby_properties_notification__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t galaxy__common__protocols__peer_to_peer__lobby_properties_notification__pack
                     (const Galaxy__Common__Protocols__PeerToPeer__LobbyPropertiesNotification *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &galaxy__common__protocols__peer_to_peer__lobby_properties_notification__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t galaxy__common__protocols__peer_to_peer__lobby_properties_notification__pack_to_buffer
                     (const Galaxy__Common__Protocols__PeerToPeer__LobbyPropertiesNotification *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &galaxy__common__protocols__peer_to_peer__lobby_properties_notification__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Galaxy__Common__Protocols__PeerToPeer__LobbyPropertiesNotification *
       galaxy__common__protocols__peer_to_peer__lobby_properties_notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Galaxy__Common__Protocols__PeerToPeer__LobbyPropertiesNotification *)
     protobuf_c_message_unpack (&galaxy__common__protocols__peer_to_peer__lobby_properties_notification__descriptor,
                                allocator, len, data);
}
void   galaxy__common__protocols__peer_to_peer__lobby_properties_notification__free_unpacked
                     (Galaxy__Common__Protocols__PeerToPeer__LobbyPropertiesNotification *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &galaxy__common__protocols__peer_to_peer__lobby_properties_notification__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   galaxy__common__protocols__peer_to_peer__lobby_member_properties_notification__init
                     (Galaxy__Common__Protocols__PeerToPeer__LobbyMemberPropertiesNotification         *message)
{
  static const Galaxy__Common__Protocols__PeerToPeer__LobbyMemberPropertiesNotification init_value = GALAXY__COMMON__PROTOCOLS__PEER_TO_PEER__LOBBY_MEMBER_PROPERTIES_NOTIFICATION__INIT;
  *message = init_value;
}
size_t galaxy__common__protocols__peer_to_peer__lobby_member_properties_notification__get_packed_size
                     (const Galaxy__Common__Protocols__PeerToPeer__LobbyMemberPropertiesNotification *message)
{
  assert(message->base.descriptor == &galaxy__common__protocols__peer_to_peer__lobby_member_properties_notification__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t galaxy__common__protocols__peer_to_peer__lobby_member_properties_notification__pack
                     (const Galaxy__Common__Protocols__PeerToPeer__LobbyMemberPropertiesNotification *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &galaxy__common__protocols__peer_to_peer__lobby_member_properties_notification__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t galaxy__common__protocols__peer_to_peer__lobby_member_properties_notification__pack_to_buffer
                     (const Galaxy__Common__Protocols__PeerToPeer__LobbyMemberPropertiesNotification *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &galaxy__common__protocols__peer_to_peer__lobby_member_properties_notification__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Galaxy__Common__Protocols__PeerToPeer__LobbyMemberPropertiesNotification *
       galaxy__common__protocols__peer_to_peer__lobby_member_properties_notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Galaxy__Common__Protocols__PeerToPeer__LobbyMemberPropertiesNotification *)
     protobuf_c_message_unpack (&galaxy__common__protocols__peer_to_peer__lobby_member_properties_notification__descriptor,
                                allocator, len, data);
}
void   galaxy__common__protocols__peer_to_peer__lobby_member_properties_notification__free_unpacked
                     (Galaxy__Common__Protocols__PeerToPeer__LobbyMemberPropertiesNotification *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &galaxy__common__protocols__peer_to_peer__lobby_member_properties_notification__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   galaxy__common__protocols__peer_to_peer__custom_packet__init
                     (Galaxy__Common__Protocols__PeerToPeer__CustomPacket         *message)
{
  static const Galaxy__Common__Protocols__PeerToPeer__CustomPacket init_value = GALAXY__COMMON__PROTOCOLS__PEER_TO_PEER__CUSTOM_PACKET__INIT;
  *message = init_value;
}
size_t galaxy__common__protocols__peer_to_peer__custom_packet__get_packed_size
                     (const Galaxy__Common__Protocols__PeerToPeer__CustomPacket *message)
{
  assert(message->base.descriptor == &galaxy__common__protocols__peer_to_peer__custom_packet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t galaxy__common__protocols__peer_to_peer__custom_packet__pack
                     (const Galaxy__Common__Protocols__PeerToPeer__CustomPacket *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &galaxy__common__protocols__peer_to_peer__custom_packet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t galaxy__common__protocols__peer_to_peer__custom_packet__pack_to_buffer
                     (const Galaxy__Common__Protocols__PeerToPeer__CustomPacket *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &galaxy__common__protocols__peer_to_peer__custom_packet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Galaxy__Common__Protocols__PeerToPeer__CustomPacket *
       galaxy__common__protocols__peer_to_peer__custom_packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Galaxy__Common__Protocols__PeerToPeer__CustomPacket *)
     protobuf_c_message_unpack (&galaxy__common__protocols__peer_to_peer__custom_packet__descriptor,
                                allocator, len, data);
}
void   galaxy__common__protocols__peer_to_peer__custom_packet__free_unpacked
                     (Galaxy__Common__Protocols__PeerToPeer__CustomPacket *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &galaxy__common__protocols__peer_to_peer__custom_packet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   galaxy__common__protocols__peer_to_peer__lobby_message__init
                     (Galaxy__Common__Protocols__PeerToPeer__LobbyMessage         *message)
{
  static const Galaxy__Common__Protocols__PeerToPeer__LobbyMessage init_value = GALAXY__COMMON__PROTOCOLS__PEER_TO_PEER__LOBBY_MESSAGE__INIT;
  *message = init_value;
}
size_t galaxy__common__protocols__peer_to_peer__lobby_message__get_packed_size
                     (const Galaxy__Common__Protocols__PeerToPeer__LobbyMessage *message)
{
  assert(message->base.descriptor == &galaxy__common__protocols__peer_to_peer__lobby_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t galaxy__common__protocols__peer_to_peer__lobby_message__pack
                     (const Galaxy__Common__Protocols__PeerToPeer__LobbyMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &galaxy__common__protocols__peer_to_peer__lobby_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t galaxy__common__protocols__peer_to_peer__lobby_message__pack_to_buffer
                     (const Galaxy__Common__Protocols__PeerToPeer__LobbyMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &galaxy__common__protocols__peer_to_peer__lobby_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Galaxy__Common__Protocols__PeerToPeer__LobbyMessage *
       galaxy__common__protocols__peer_to_peer__lobby_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Galaxy__Common__Protocols__PeerToPeer__LobbyMessage *)
     protobuf_c_message_unpack (&galaxy__common__protocols__peer_to_peer__lobby_message__descriptor,
                                allocator, len, data);
}
void   galaxy__common__protocols__peer_to_peer__lobby_message__free_unpacked
                     (Galaxy__Common__Protocols__PeerToPeer__LobbyMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &galaxy__common__protocols__peer_to_peer__lobby_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor galaxy__common__protocols__peer_to_peer__lobby_properties_notification__field_descriptors[5] =
{
  {
    "lobby_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Galaxy__Common__Protocols__PeerToPeer__LobbyPropertiesNotification, has_lobby_id),
    offsetof(Galaxy__Common__Protocols__PeerToPeer__LobbyPropertiesNotification, lobby_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "properties",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Galaxy__Common__Protocols__PeerToPeer__LobbyPropertiesNotification, n_properties),
    offsetof(Galaxy__Common__Protocols__PeerToPeer__LobbyPropertiesNotification, properties),
    &galaxy__common__protocols__peer_common__property__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "member_max_count",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Galaxy__Common__Protocols__PeerToPeer__LobbyPropertiesNotification, has_member_max_count),
    offsetof(Galaxy__Common__Protocols__PeerToPeer__LobbyPropertiesNotification, member_max_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lobby_type",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Galaxy__Common__Protocols__PeerToPeer__LobbyPropertiesNotification, has_lobby_type),
    offsetof(Galaxy__Common__Protocols__PeerToPeer__LobbyPropertiesNotification, lobby_type),
    &galaxy__common__protocols__peer_to_peer__lobby_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "joinable",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Galaxy__Common__Protocols__PeerToPeer__LobbyPropertiesNotification, has_joinable),
    offsetof(Galaxy__Common__Protocols__PeerToPeer__LobbyPropertiesNotification, joinable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned galaxy__common__protocols__peer_to_peer__lobby_properties_notification__field_indices_by_name[] = {
  4,   /* field[4] = joinable */
  0,   /* field[0] = lobby_id */
  3,   /* field[3] = lobby_type */
  2,   /* field[2] = member_max_count */
  1,   /* field[1] = properties */
};
static const ProtobufCIntRange galaxy__common__protocols__peer_to_peer__lobby_properties_notification__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor galaxy__common__protocols__peer_to_peer__lobby_properties_notification__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "galaxy.common.protocols.peer_to_peer.LobbyPropertiesNotification",
  "LobbyPropertiesNotification",
  "Galaxy__Common__Protocols__PeerToPeer__LobbyPropertiesNotification",
  "galaxy.common.protocols.peer_to_peer",
  sizeof(Galaxy__Common__Protocols__PeerToPeer__LobbyPropertiesNotification),
  5,
  galaxy__common__protocols__peer_to_peer__lobby_properties_notification__field_descriptors,
  galaxy__common__protocols__peer_to_peer__lobby_properties_notification__field_indices_by_name,
  1,  galaxy__common__protocols__peer_to_peer__lobby_properties_notification__number_ranges,
  (ProtobufCMessageInit) galaxy__common__protocols__peer_to_peer__lobby_properties_notification__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor galaxy__common__protocols__peer_to_peer__lobby_member_properties_notification__field_descriptors[2] =
{
  {
    "lobby_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Galaxy__Common__Protocols__PeerToPeer__LobbyMemberPropertiesNotification, has_lobby_id),
    offsetof(Galaxy__Common__Protocols__PeerToPeer__LobbyMemberPropertiesNotification, lobby_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "properties",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Galaxy__Common__Protocols__PeerToPeer__LobbyMemberPropertiesNotification, n_properties),
    offsetof(Galaxy__Common__Protocols__PeerToPeer__LobbyMemberPropertiesNotification, properties),
    &galaxy__common__protocols__peer_common__property__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned galaxy__common__protocols__peer_to_peer__lobby_member_properties_notification__field_indices_by_name[] = {
  0,   /* field[0] = lobby_id */
  1,   /* field[1] = properties */
};
static const ProtobufCIntRange galaxy__common__protocols__peer_to_peer__lobby_member_properties_notification__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor galaxy__common__protocols__peer_to_peer__lobby_member_properties_notification__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "galaxy.common.protocols.peer_to_peer.LobbyMemberPropertiesNotification",
  "LobbyMemberPropertiesNotification",
  "Galaxy__Common__Protocols__PeerToPeer__LobbyMemberPropertiesNotification",
  "galaxy.common.protocols.peer_to_peer",
  sizeof(Galaxy__Common__Protocols__PeerToPeer__LobbyMemberPropertiesNotification),
  2,
  galaxy__common__protocols__peer_to_peer__lobby_member_properties_notification__field_descriptors,
  galaxy__common__protocols__peer_to_peer__lobby_member_properties_notification__field_indices_by_name,
  2,  galaxy__common__protocols__peer_to_peer__lobby_member_properties_notification__number_ranges,
  (ProtobufCMessageInit) galaxy__common__protocols__peer_to_peer__lobby_member_properties_notification__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor galaxy__common__protocols__peer_to_peer__custom_packet__field_descriptors[4] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Galaxy__Common__Protocols__PeerToPeer__CustomPacket, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Galaxy__Common__Protocols__PeerToPeer__CustomPacket, has_channel),
    offsetof(Galaxy__Common__Protocols__PeerToPeer__CustomPacket, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lobby_id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Galaxy__Common__Protocols__PeerToPeer__CustomPacket, has_lobby_id),
    offsetof(Galaxy__Common__Protocols__PeerToPeer__CustomPacket, lobby_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Galaxy__Common__Protocols__PeerToPeer__CustomPacket, has_seq),
    offsetof(Galaxy__Common__Protocols__PeerToPeer__CustomPacket, seq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned galaxy__common__protocols__peer_to_peer__custom_packet__field_indices_by_name[] = {
  1,   /* field[1] = channel */
  0,   /* field[0] = data */
  2,   /* field[2] = lobby_id */
  3,   /* field[3] = seq */
};
static const ProtobufCIntRange galaxy__common__protocols__peer_to_peer__custom_packet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor galaxy__common__protocols__peer_to_peer__custom_packet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "galaxy.common.protocols.peer_to_peer.CustomPacket",
  "CustomPacket",
  "Galaxy__Common__Protocols__PeerToPeer__CustomPacket",
  "galaxy.common.protocols.peer_to_peer",
  sizeof(Galaxy__Common__Protocols__PeerToPeer__CustomPacket),
  4,
  galaxy__common__protocols__peer_to_peer__custom_packet__field_descriptors,
  galaxy__common__protocols__peer_to_peer__custom_packet__field_indices_by_name,
  1,  galaxy__common__protocols__peer_to_peer__custom_packet__number_ranges,
  (ProtobufCMessageInit) galaxy__common__protocols__peer_to_peer__custom_packet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor galaxy__common__protocols__peer_to_peer__lobby_message__field_descriptors[2] =
{
  {
    "lobby_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Galaxy__Common__Protocols__PeerToPeer__LobbyMessage, has_lobby_id),
    offsetof(Galaxy__Common__Protocols__PeerToPeer__LobbyMessage, lobby_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Galaxy__Common__Protocols__PeerToPeer__LobbyMessage, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned galaxy__common__protocols__peer_to_peer__lobby_message__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = lobby_id */
};
static const ProtobufCIntRange galaxy__common__protocols__peer_to_peer__lobby_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor galaxy__common__protocols__peer_to_peer__lobby_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "galaxy.common.protocols.peer_to_peer.LobbyMessage",
  "LobbyMessage",
  "Galaxy__Common__Protocols__PeerToPeer__LobbyMessage",
  "galaxy.common.protocols.peer_to_peer",
  sizeof(Galaxy__Common__Protocols__PeerToPeer__LobbyMessage),
  2,
  galaxy__common__protocols__peer_to_peer__lobby_message__field_descriptors,
  galaxy__common__protocols__peer_to_peer__lobby_message__field_indices_by_name,
  1,  galaxy__common__protocols__peer_to_peer__lobby_message__number_ranges,
  (ProtobufCMessageInit) galaxy__common__protocols__peer_to_peer__lobby_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue galaxy__common__protocols__peer_to_peer__message_type__enum_values_by_number[5] =
{
  { "UNKNOWN_MESSAGE", "GALAXY__COMMON__PROTOCOLS__PEER_TO_PEER__MESSAGE_TYPE__UNKNOWN_MESSAGE", 0 },
  { "LOBBY_PROPERTIES_NOTIFICATION", "GALAXY__COMMON__PROTOCOLS__PEER_TO_PEER__MESSAGE_TYPE__LOBBY_PROPERTIES_NOTIFICATION", 1 },
  { "LOBBY_MEMBER_PROPERTIES_NOTIFICATION", "GALAXY__COMMON__PROTOCOLS__PEER_TO_PEER__MESSAGE_TYPE__LOBBY_MEMBER_PROPERTIES_NOTIFICATION", 2 },
  { "CUSTOM_PACKET", "GALAXY__COMMON__PROTOCOLS__PEER_TO_PEER__MESSAGE_TYPE__CUSTOM_PACKET", 3 },
  { "LOBBY_MESSAGE", "GALAXY__COMMON__PROTOCOLS__PEER_TO_PEER__MESSAGE_TYPE__LOBBY_MESSAGE", 4 },
};
static const ProtobufCIntRange galaxy__common__protocols__peer_to_peer__message_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex galaxy__common__protocols__peer_to_peer__message_type__enum_values_by_name[5] =
{
  { "CUSTOM_PACKET", 3 },
  { "LOBBY_MEMBER_PROPERTIES_NOTIFICATION", 2 },
  { "LOBBY_MESSAGE", 4 },
  { "LOBBY_PROPERTIES_NOTIFICATION", 1 },
  { "UNKNOWN_MESSAGE", 0 },
};
const ProtobufCEnumDescriptor galaxy__common__protocols__peer_to_peer__message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "galaxy.common.protocols.peer_to_peer.MessageType",
  "MessageType",
  "Galaxy__Common__Protocols__PeerToPeer__MessageType",
  "galaxy.common.protocols.peer_to_peer",
  5,
  galaxy__common__protocols__peer_to_peer__message_type__enum_values_by_number,
  5,
  galaxy__common__protocols__peer_to_peer__message_type__enum_values_by_name,
  1,
  galaxy__common__protocols__peer_to_peer__message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue galaxy__common__protocols__peer_to_peer__lobby_type__enum_values_by_number[4] =
{
  { "LOBBY_TYPE_PRIVATE", "GALAXY__COMMON__PROTOCOLS__PEER_TO_PEER__LOBBY_TYPE__LOBBY_TYPE_PRIVATE", 0 },
  { "LOBBY_TYPE_FRIENDS_ONLY", "GALAXY__COMMON__PROTOCOLS__PEER_TO_PEER__LOBBY_TYPE__LOBBY_TYPE_FRIENDS_ONLY", 1 },
  { "LOBBY_TYPE_PUBLIC", "GALAXY__COMMON__PROTOCOLS__PEER_TO_PEER__LOBBY_TYPE__LOBBY_TYPE_PUBLIC", 2 },
  { "LOBBY_TYPE_INVISIBLE_TO_FRIENDS", "GALAXY__COMMON__PROTOCOLS__PEER_TO_PEER__LOBBY_TYPE__LOBBY_TYPE_INVISIBLE_TO_FRIENDS", 3 },
};
static const ProtobufCIntRange galaxy__common__protocols__peer_to_peer__lobby_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex galaxy__common__protocols__peer_to_peer__lobby_type__enum_values_by_name[4] =
{
  { "LOBBY_TYPE_FRIENDS_ONLY", 1 },
  { "LOBBY_TYPE_INVISIBLE_TO_FRIENDS", 3 },
  { "LOBBY_TYPE_PRIVATE", 0 },
  { "LOBBY_TYPE_PUBLIC", 2 },
};
const ProtobufCEnumDescriptor galaxy__common__protocols__peer_to_peer__lobby_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "galaxy.common.protocols.peer_to_peer.LobbyType",
  "LobbyType",
  "Galaxy__Common__Protocols__PeerToPeer__LobbyType",
  "galaxy.common.protocols.peer_to_peer",
  4,
  galaxy__common__protocols__peer_to_peer__lobby_type__enum_values_by_number,
  4,
  galaxy__common__protocols__peer_to_peer__lobby_type__enum_values_by_name,
  1,
  galaxy__common__protocols__peer_to_peer__lobby_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
