/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: galaxy.protocols.webbroker_service.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "galaxy.protocols.webbroker_service.pb-c.h"
void   galaxy__protocols__webbroker_service__auth_request__init
                     (Galaxy__Protocols__WebbrokerService__AuthRequest         *message)
{
  static const Galaxy__Protocols__WebbrokerService__AuthRequest init_value = GALAXY__PROTOCOLS__WEBBROKER_SERVICE__AUTH_REQUEST__INIT;
  *message = init_value;
}
size_t galaxy__protocols__webbroker_service__auth_request__get_packed_size
                     (const Galaxy__Protocols__WebbrokerService__AuthRequest *message)
{
  assert(message->base.descriptor == &galaxy__protocols__webbroker_service__auth_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t galaxy__protocols__webbroker_service__auth_request__pack
                     (const Galaxy__Protocols__WebbrokerService__AuthRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &galaxy__protocols__webbroker_service__auth_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t galaxy__protocols__webbroker_service__auth_request__pack_to_buffer
                     (const Galaxy__Protocols__WebbrokerService__AuthRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &galaxy__protocols__webbroker_service__auth_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Galaxy__Protocols__WebbrokerService__AuthRequest *
       galaxy__protocols__webbroker_service__auth_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Galaxy__Protocols__WebbrokerService__AuthRequest *)
     protobuf_c_message_unpack (&galaxy__protocols__webbroker_service__auth_request__descriptor,
                                allocator, len, data);
}
void   galaxy__protocols__webbroker_service__auth_request__free_unpacked
                     (Galaxy__Protocols__WebbrokerService__AuthRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &galaxy__protocols__webbroker_service__auth_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   galaxy__protocols__webbroker_service__subscribe_topic_request__init
                     (Galaxy__Protocols__WebbrokerService__SubscribeTopicRequest         *message)
{
  static const Galaxy__Protocols__WebbrokerService__SubscribeTopicRequest init_value = GALAXY__PROTOCOLS__WEBBROKER_SERVICE__SUBSCRIBE_TOPIC_REQUEST__INIT;
  *message = init_value;
}
size_t galaxy__protocols__webbroker_service__subscribe_topic_request__get_packed_size
                     (const Galaxy__Protocols__WebbrokerService__SubscribeTopicRequest *message)
{
  assert(message->base.descriptor == &galaxy__protocols__webbroker_service__subscribe_topic_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t galaxy__protocols__webbroker_service__subscribe_topic_request__pack
                     (const Galaxy__Protocols__WebbrokerService__SubscribeTopicRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &galaxy__protocols__webbroker_service__subscribe_topic_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t galaxy__protocols__webbroker_service__subscribe_topic_request__pack_to_buffer
                     (const Galaxy__Protocols__WebbrokerService__SubscribeTopicRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &galaxy__protocols__webbroker_service__subscribe_topic_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Galaxy__Protocols__WebbrokerService__SubscribeTopicRequest *
       galaxy__protocols__webbroker_service__subscribe_topic_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Galaxy__Protocols__WebbrokerService__SubscribeTopicRequest *)
     protobuf_c_message_unpack (&galaxy__protocols__webbroker_service__subscribe_topic_request__descriptor,
                                allocator, len, data);
}
void   galaxy__protocols__webbroker_service__subscribe_topic_request__free_unpacked
                     (Galaxy__Protocols__WebbrokerService__SubscribeTopicRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &galaxy__protocols__webbroker_service__subscribe_topic_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   galaxy__protocols__webbroker_service__subscribe_topic_response__init
                     (Galaxy__Protocols__WebbrokerService__SubscribeTopicResponse         *message)
{
  static const Galaxy__Protocols__WebbrokerService__SubscribeTopicResponse init_value = GALAXY__PROTOCOLS__WEBBROKER_SERVICE__SUBSCRIBE_TOPIC_RESPONSE__INIT;
  *message = init_value;
}
size_t galaxy__protocols__webbroker_service__subscribe_topic_response__get_packed_size
                     (const Galaxy__Protocols__WebbrokerService__SubscribeTopicResponse *message)
{
  assert(message->base.descriptor == &galaxy__protocols__webbroker_service__subscribe_topic_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t galaxy__protocols__webbroker_service__subscribe_topic_response__pack
                     (const Galaxy__Protocols__WebbrokerService__SubscribeTopicResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &galaxy__protocols__webbroker_service__subscribe_topic_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t galaxy__protocols__webbroker_service__subscribe_topic_response__pack_to_buffer
                     (const Galaxy__Protocols__WebbrokerService__SubscribeTopicResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &galaxy__protocols__webbroker_service__subscribe_topic_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Galaxy__Protocols__WebbrokerService__SubscribeTopicResponse *
       galaxy__protocols__webbroker_service__subscribe_topic_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Galaxy__Protocols__WebbrokerService__SubscribeTopicResponse *)
     protobuf_c_message_unpack (&galaxy__protocols__webbroker_service__subscribe_topic_response__descriptor,
                                allocator, len, data);
}
void   galaxy__protocols__webbroker_service__subscribe_topic_response__free_unpacked
                     (Galaxy__Protocols__WebbrokerService__SubscribeTopicResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &galaxy__protocols__webbroker_service__subscribe_topic_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   galaxy__protocols__webbroker_service__message_from_topic__init
                     (Galaxy__Protocols__WebbrokerService__MessageFromTopic         *message)
{
  static const Galaxy__Protocols__WebbrokerService__MessageFromTopic init_value = GALAXY__PROTOCOLS__WEBBROKER_SERVICE__MESSAGE_FROM_TOPIC__INIT;
  *message = init_value;
}
size_t galaxy__protocols__webbroker_service__message_from_topic__get_packed_size
                     (const Galaxy__Protocols__WebbrokerService__MessageFromTopic *message)
{
  assert(message->base.descriptor == &galaxy__protocols__webbroker_service__message_from_topic__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t galaxy__protocols__webbroker_service__message_from_topic__pack
                     (const Galaxy__Protocols__WebbrokerService__MessageFromTopic *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &galaxy__protocols__webbroker_service__message_from_topic__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t galaxy__protocols__webbroker_service__message_from_topic__pack_to_buffer
                     (const Galaxy__Protocols__WebbrokerService__MessageFromTopic *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &galaxy__protocols__webbroker_service__message_from_topic__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Galaxy__Protocols__WebbrokerService__MessageFromTopic *
       galaxy__protocols__webbroker_service__message_from_topic__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Galaxy__Protocols__WebbrokerService__MessageFromTopic *)
     protobuf_c_message_unpack (&galaxy__protocols__webbroker_service__message_from_topic__descriptor,
                                allocator, len, data);
}
void   galaxy__protocols__webbroker_service__message_from_topic__free_unpacked
                     (Galaxy__Protocols__WebbrokerService__MessageFromTopic *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &galaxy__protocols__webbroker_service__message_from_topic__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor galaxy__protocols__webbroker_service__auth_request__field_descriptors[1] =
{
  {
    "auth_token",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Galaxy__Protocols__WebbrokerService__AuthRequest, auth_token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned galaxy__protocols__webbroker_service__auth_request__field_indices_by_name[] = {
  0,   /* field[0] = auth_token */
};
static const ProtobufCIntRange galaxy__protocols__webbroker_service__auth_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor galaxy__protocols__webbroker_service__auth_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "galaxy.protocols.webbroker_service.AuthRequest",
  "AuthRequest",
  "Galaxy__Protocols__WebbrokerService__AuthRequest",
  "galaxy.protocols.webbroker_service",
  sizeof(Galaxy__Protocols__WebbrokerService__AuthRequest),
  1,
  galaxy__protocols__webbroker_service__auth_request__field_descriptors,
  galaxy__protocols__webbroker_service__auth_request__field_indices_by_name,
  1,  galaxy__protocols__webbroker_service__auth_request__number_ranges,
  (ProtobufCMessageInit) galaxy__protocols__webbroker_service__auth_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor galaxy__protocols__webbroker_service__subscribe_topic_request__field_descriptors[1] =
{
  {
    "topic",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Galaxy__Protocols__WebbrokerService__SubscribeTopicRequest, topic),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned galaxy__protocols__webbroker_service__subscribe_topic_request__field_indices_by_name[] = {
  0,   /* field[0] = topic */
};
static const ProtobufCIntRange galaxy__protocols__webbroker_service__subscribe_topic_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor galaxy__protocols__webbroker_service__subscribe_topic_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "galaxy.protocols.webbroker_service.SubscribeTopicRequest",
  "SubscribeTopicRequest",
  "Galaxy__Protocols__WebbrokerService__SubscribeTopicRequest",
  "galaxy.protocols.webbroker_service",
  sizeof(Galaxy__Protocols__WebbrokerService__SubscribeTopicRequest),
  1,
  galaxy__protocols__webbroker_service__subscribe_topic_request__field_descriptors,
  galaxy__protocols__webbroker_service__subscribe_topic_request__field_indices_by_name,
  1,  galaxy__protocols__webbroker_service__subscribe_topic_request__number_ranges,
  (ProtobufCMessageInit) galaxy__protocols__webbroker_service__subscribe_topic_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor galaxy__protocols__webbroker_service__subscribe_topic_response__field_descriptors[1] =
{
  {
    "topic",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Galaxy__Protocols__WebbrokerService__SubscribeTopicResponse, topic),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned galaxy__protocols__webbroker_service__subscribe_topic_response__field_indices_by_name[] = {
  0,   /* field[0] = topic */
};
static const ProtobufCIntRange galaxy__protocols__webbroker_service__subscribe_topic_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor galaxy__protocols__webbroker_service__subscribe_topic_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "galaxy.protocols.webbroker_service.SubscribeTopicResponse",
  "SubscribeTopicResponse",
  "Galaxy__Protocols__WebbrokerService__SubscribeTopicResponse",
  "galaxy.protocols.webbroker_service",
  sizeof(Galaxy__Protocols__WebbrokerService__SubscribeTopicResponse),
  1,
  galaxy__protocols__webbroker_service__subscribe_topic_response__field_descriptors,
  galaxy__protocols__webbroker_service__subscribe_topic_response__field_indices_by_name,
  1,  galaxy__protocols__webbroker_service__subscribe_topic_response__number_ranges,
  (ProtobufCMessageInit) galaxy__protocols__webbroker_service__subscribe_topic_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor galaxy__protocols__webbroker_service__message_from_topic__field_descriptors[3] =
{
  {
    "topic",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Galaxy__Protocols__WebbrokerService__MessageFromTopic, topic),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Galaxy__Protocols__WebbrokerService__MessageFromTopic, content),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Galaxy__Protocols__WebbrokerService__MessageFromTopic, has_id),
    offsetof(Galaxy__Protocols__WebbrokerService__MessageFromTopic, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned galaxy__protocols__webbroker_service__message_from_topic__field_indices_by_name[] = {
  1,   /* field[1] = content */
  2,   /* field[2] = id */
  0,   /* field[0] = topic */
};
static const ProtobufCIntRange galaxy__protocols__webbroker_service__message_from_topic__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor galaxy__protocols__webbroker_service__message_from_topic__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "galaxy.protocols.webbroker_service.MessageFromTopic",
  "MessageFromTopic",
  "Galaxy__Protocols__WebbrokerService__MessageFromTopic",
  "galaxy.protocols.webbroker_service",
  sizeof(Galaxy__Protocols__WebbrokerService__MessageFromTopic),
  3,
  galaxy__protocols__webbroker_service__message_from_topic__field_descriptors,
  galaxy__protocols__webbroker_service__message_from_topic__field_indices_by_name,
  1,  galaxy__protocols__webbroker_service__message_from_topic__number_ranges,
  (ProtobufCMessageInit) galaxy__protocols__webbroker_service__message_from_topic__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue galaxy__protocols__webbroker_service__message_sort__enum_values_by_number[1] =
{
  { "MESSAGE_SORT", "GALAXY__PROTOCOLS__WEBBROKER_SERVICE__MESSAGE_SORT__MESSAGE_SORT", 2 },
};
static const ProtobufCIntRange galaxy__protocols__webbroker_service__message_sort__value_ranges[] = {
{2, 0},{0, 1}
};
static const ProtobufCEnumValueIndex galaxy__protocols__webbroker_service__message_sort__enum_values_by_name[1] =
{
  { "MESSAGE_SORT", 0 },
};
const ProtobufCEnumDescriptor galaxy__protocols__webbroker_service__message_sort__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "galaxy.protocols.webbroker_service.MessageSort",
  "MessageSort",
  "Galaxy__Protocols__WebbrokerService__MessageSort",
  "galaxy.protocols.webbroker_service",
  1,
  galaxy__protocols__webbroker_service__message_sort__enum_values_by_number,
  1,
  galaxy__protocols__webbroker_service__message_sort__enum_values_by_name,
  1,
  galaxy__protocols__webbroker_service__message_sort__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue galaxy__protocols__webbroker_service__message_type__enum_values_by_number[6] =
{
  { "UNKNOWN_MESSAGE", "GALAXY__PROTOCOLS__WEBBROKER_SERVICE__MESSAGE_TYPE__UNKNOWN_MESSAGE", 0 },
  { "AUTH_REQUEST", "GALAXY__PROTOCOLS__WEBBROKER_SERVICE__MESSAGE_TYPE__AUTH_REQUEST", 1 },
  { "AUTH_RESPONSE", "GALAXY__PROTOCOLS__WEBBROKER_SERVICE__MESSAGE_TYPE__AUTH_RESPONSE", 2 },
  { "SUBSCRIBE_TOPIC_REQUEST", "GALAXY__PROTOCOLS__WEBBROKER_SERVICE__MESSAGE_TYPE__SUBSCRIBE_TOPIC_REQUEST", 3 },
  { "SUBSCRIBE_TOPIC_RESPONSE", "GALAXY__PROTOCOLS__WEBBROKER_SERVICE__MESSAGE_TYPE__SUBSCRIBE_TOPIC_RESPONSE", 4 },
  { "MESSAGE_FROM_TOPIC", "GALAXY__PROTOCOLS__WEBBROKER_SERVICE__MESSAGE_TYPE__MESSAGE_FROM_TOPIC", 5 },
};
static const ProtobufCIntRange galaxy__protocols__webbroker_service__message_type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex galaxy__protocols__webbroker_service__message_type__enum_values_by_name[6] =
{
  { "AUTH_REQUEST", 1 },
  { "AUTH_RESPONSE", 2 },
  { "MESSAGE_FROM_TOPIC", 5 },
  { "SUBSCRIBE_TOPIC_REQUEST", 3 },
  { "SUBSCRIBE_TOPIC_RESPONSE", 4 },
  { "UNKNOWN_MESSAGE", 0 },
};
const ProtobufCEnumDescriptor galaxy__protocols__webbroker_service__message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "galaxy.protocols.webbroker_service.MessageType",
  "MessageType",
  "Galaxy__Protocols__WebbrokerService__MessageType",
  "galaxy.protocols.webbroker_service",
  6,
  galaxy__protocols__webbroker_service__message_type__enum_values_by_number,
  6,
  galaxy__protocols__webbroker_service__message_type__enum_values_by_name,
  1,
  galaxy__protocols__webbroker_service__message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
