/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: galaxy.protocols.overlay_for_peer.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "galaxy.protocols.overlay_for_peer.pb-c.h"
void   galaxy__protocols__overlay_for_peer__state_change_notification__init
                     (Galaxy__Protocols__OverlayForPeer__StateChangeNotification         *message)
{
  static const Galaxy__Protocols__OverlayForPeer__StateChangeNotification init_value = GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__STATE_CHANGE_NOTIFICATION__INIT;
  *message = init_value;
}
size_t galaxy__protocols__overlay_for_peer__state_change_notification__get_packed_size
                     (const Galaxy__Protocols__OverlayForPeer__StateChangeNotification *message)
{
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__state_change_notification__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t galaxy__protocols__overlay_for_peer__state_change_notification__pack
                     (const Galaxy__Protocols__OverlayForPeer__StateChangeNotification *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__state_change_notification__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t galaxy__protocols__overlay_for_peer__state_change_notification__pack_to_buffer
                     (const Galaxy__Protocols__OverlayForPeer__StateChangeNotification *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__state_change_notification__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Galaxy__Protocols__OverlayForPeer__StateChangeNotification *
       galaxy__protocols__overlay_for_peer__state_change_notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Galaxy__Protocols__OverlayForPeer__StateChangeNotification *)
     protobuf_c_message_unpack (&galaxy__protocols__overlay_for_peer__state_change_notification__descriptor,
                                allocator, len, data);
}
void   galaxy__protocols__overlay_for_peer__state_change_notification__free_unpacked
                     (Galaxy__Protocols__OverlayForPeer__StateChangeNotification *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__state_change_notification__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   galaxy__protocols__overlay_for_peer__visibility_change_notification__init
                     (Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification         *message)
{
  static const Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification init_value = GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__VISIBILITY_CHANGE_NOTIFICATION__INIT;
  *message = init_value;
}
size_t galaxy__protocols__overlay_for_peer__visibility_change_notification__get_packed_size
                     (const Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification *message)
{
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__visibility_change_notification__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t galaxy__protocols__overlay_for_peer__visibility_change_notification__pack
                     (const Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__visibility_change_notification__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t galaxy__protocols__overlay_for_peer__visibility_change_notification__pack_to_buffer
                     (const Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__visibility_change_notification__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification *
       galaxy__protocols__overlay_for_peer__visibility_change_notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification *)
     protobuf_c_message_unpack (&galaxy__protocols__overlay_for_peer__visibility_change_notification__descriptor,
                                allocator, len, data);
}
void   galaxy__protocols__overlay_for_peer__visibility_change_notification__free_unpacked
                     (Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__visibility_change_notification__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   galaxy__protocols__overlay_for_peer__show_invitation_dialog__init
                     (Galaxy__Protocols__OverlayForPeer__ShowInvitationDialog         *message)
{
  static const Galaxy__Protocols__OverlayForPeer__ShowInvitationDialog init_value = GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__SHOW_INVITATION_DIALOG__INIT;
  *message = init_value;
}
size_t galaxy__protocols__overlay_for_peer__show_invitation_dialog__get_packed_size
                     (const Galaxy__Protocols__OverlayForPeer__ShowInvitationDialog *message)
{
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__show_invitation_dialog__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t galaxy__protocols__overlay_for_peer__show_invitation_dialog__pack
                     (const Galaxy__Protocols__OverlayForPeer__ShowInvitationDialog *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__show_invitation_dialog__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t galaxy__protocols__overlay_for_peer__show_invitation_dialog__pack_to_buffer
                     (const Galaxy__Protocols__OverlayForPeer__ShowInvitationDialog *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__show_invitation_dialog__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Galaxy__Protocols__OverlayForPeer__ShowInvitationDialog *
       galaxy__protocols__overlay_for_peer__show_invitation_dialog__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Galaxy__Protocols__OverlayForPeer__ShowInvitationDialog *)
     protobuf_c_message_unpack (&galaxy__protocols__overlay_for_peer__show_invitation_dialog__descriptor,
                                allocator, len, data);
}
void   galaxy__protocols__overlay_for_peer__show_invitation_dialog__free_unpacked
                     (Galaxy__Protocols__OverlayForPeer__ShowInvitationDialog *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__show_invitation_dialog__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   galaxy__protocols__overlay_for_peer__game_join_request_notification__init
                     (Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification         *message)
{
  static const Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification init_value = GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__GAME_JOIN_REQUEST_NOTIFICATION__INIT;
  *message = init_value;
}
size_t galaxy__protocols__overlay_for_peer__game_join_request_notification__get_packed_size
                     (const Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification *message)
{
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__game_join_request_notification__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t galaxy__protocols__overlay_for_peer__game_join_request_notification__pack
                     (const Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__game_join_request_notification__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t galaxy__protocols__overlay_for_peer__game_join_request_notification__pack_to_buffer
                     (const Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__game_join_request_notification__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification *
       galaxy__protocols__overlay_for_peer__game_join_request_notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification *)
     protobuf_c_message_unpack (&galaxy__protocols__overlay_for_peer__game_join_request_notification__descriptor,
                                allocator, len, data);
}
void   galaxy__protocols__overlay_for_peer__game_join_request_notification__free_unpacked
                     (Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__game_join_request_notification__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   galaxy__protocols__overlay_for_peer__show_web_page__init
                     (Galaxy__Protocols__OverlayForPeer__ShowWebPage         *message)
{
  static const Galaxy__Protocols__OverlayForPeer__ShowWebPage init_value = GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__SHOW_WEB_PAGE__INIT;
  *message = init_value;
}
size_t galaxy__protocols__overlay_for_peer__show_web_page__get_packed_size
                     (const Galaxy__Protocols__OverlayForPeer__ShowWebPage *message)
{
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__show_web_page__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t galaxy__protocols__overlay_for_peer__show_web_page__pack
                     (const Galaxy__Protocols__OverlayForPeer__ShowWebPage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__show_web_page__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t galaxy__protocols__overlay_for_peer__show_web_page__pack_to_buffer
                     (const Galaxy__Protocols__OverlayForPeer__ShowWebPage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__show_web_page__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Galaxy__Protocols__OverlayForPeer__ShowWebPage *
       galaxy__protocols__overlay_for_peer__show_web_page__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Galaxy__Protocols__OverlayForPeer__ShowWebPage *)
     protobuf_c_message_unpack (&galaxy__protocols__overlay_for_peer__show_web_page__descriptor,
                                allocator, len, data);
}
void   galaxy__protocols__overlay_for_peer__show_web_page__free_unpacked
                     (Galaxy__Protocols__OverlayForPeer__ShowWebPage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__show_web_page__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   galaxy__protocols__overlay_for_peer__game_invite_sent_notification__init
                     (Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification         *message)
{
  static const Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification init_value = GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__GAME_INVITE_SENT_NOTIFICATION__INIT;
  *message = init_value;
}
size_t galaxy__protocols__overlay_for_peer__game_invite_sent_notification__get_packed_size
                     (const Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification *message)
{
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__game_invite_sent_notification__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t galaxy__protocols__overlay_for_peer__game_invite_sent_notification__pack
                     (const Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__game_invite_sent_notification__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t galaxy__protocols__overlay_for_peer__game_invite_sent_notification__pack_to_buffer
                     (const Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__game_invite_sent_notification__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification *
       galaxy__protocols__overlay_for_peer__game_invite_sent_notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification *)
     protobuf_c_message_unpack (&galaxy__protocols__overlay_for_peer__game_invite_sent_notification__descriptor,
                                allocator, len, data);
}
void   galaxy__protocols__overlay_for_peer__game_invite_sent_notification__free_unpacked
                     (Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__game_invite_sent_notification__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   galaxy__protocols__overlay_for_peer__disable_popups__init
                     (Galaxy__Protocols__OverlayForPeer__DisablePopups         *message)
{
  static const Galaxy__Protocols__OverlayForPeer__DisablePopups init_value = GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__DISABLE_POPUPS__INIT;
  *message = init_value;
}
size_t galaxy__protocols__overlay_for_peer__disable_popups__get_packed_size
                     (const Galaxy__Protocols__OverlayForPeer__DisablePopups *message)
{
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__disable_popups__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t galaxy__protocols__overlay_for_peer__disable_popups__pack
                     (const Galaxy__Protocols__OverlayForPeer__DisablePopups *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__disable_popups__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t galaxy__protocols__overlay_for_peer__disable_popups__pack_to_buffer
                     (const Galaxy__Protocols__OverlayForPeer__DisablePopups *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__disable_popups__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Galaxy__Protocols__OverlayForPeer__DisablePopups *
       galaxy__protocols__overlay_for_peer__disable_popups__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Galaxy__Protocols__OverlayForPeer__DisablePopups *)
     protobuf_c_message_unpack (&galaxy__protocols__overlay_for_peer__disable_popups__descriptor,
                                allocator, len, data);
}
void   galaxy__protocols__overlay_for_peer__disable_popups__free_unpacked
                     (Galaxy__Protocols__OverlayForPeer__DisablePopups *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &galaxy__protocols__overlay_for_peer__disable_popups__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor galaxy__protocols__overlay_for_peer__state_change_notification__field_descriptors[1] =
{
  {
    "active",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Galaxy__Protocols__OverlayForPeer__StateChangeNotification, has_active),
    offsetof(Galaxy__Protocols__OverlayForPeer__StateChangeNotification, active),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned galaxy__protocols__overlay_for_peer__state_change_notification__field_indices_by_name[] = {
  0,   /* field[0] = active */
};
static const ProtobufCIntRange galaxy__protocols__overlay_for_peer__state_change_notification__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor galaxy__protocols__overlay_for_peer__state_change_notification__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "galaxy.protocols.overlay_for_peer.StateChangeNotification",
  "StateChangeNotification",
  "Galaxy__Protocols__OverlayForPeer__StateChangeNotification",
  "galaxy.protocols.overlay_for_peer",
  sizeof(Galaxy__Protocols__OverlayForPeer__StateChangeNotification),
  1,
  galaxy__protocols__overlay_for_peer__state_change_notification__field_descriptors,
  galaxy__protocols__overlay_for_peer__state_change_notification__field_indices_by_name,
  1,  galaxy__protocols__overlay_for_peer__state_change_notification__number_ranges,
  (ProtobufCMessageInit) galaxy__protocols__overlay_for_peer__state_change_notification__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor galaxy__protocols__overlay_for_peer__visibility_change_notification__field_descriptors[1] =
{
  {
    "visible",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification, has_visible),
    offsetof(Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification, visible),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned galaxy__protocols__overlay_for_peer__visibility_change_notification__field_indices_by_name[] = {
  0,   /* field[0] = visible */
};
static const ProtobufCIntRange galaxy__protocols__overlay_for_peer__visibility_change_notification__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor galaxy__protocols__overlay_for_peer__visibility_change_notification__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "galaxy.protocols.overlay_for_peer.VisibilityChangeNotification",
  "VisibilityChangeNotification",
  "Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification",
  "galaxy.protocols.overlay_for_peer",
  sizeof(Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification),
  1,
  galaxy__protocols__overlay_for_peer__visibility_change_notification__field_descriptors,
  galaxy__protocols__overlay_for_peer__visibility_change_notification__field_indices_by_name,
  1,  galaxy__protocols__overlay_for_peer__visibility_change_notification__number_ranges,
  (ProtobufCMessageInit) galaxy__protocols__overlay_for_peer__visibility_change_notification__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor galaxy__protocols__overlay_for_peer__show_invitation_dialog__field_descriptors[1] =
{
  {
    "connection_string",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Galaxy__Protocols__OverlayForPeer__ShowInvitationDialog, connection_string),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned galaxy__protocols__overlay_for_peer__show_invitation_dialog__field_indices_by_name[] = {
  0,   /* field[0] = connection_string */
};
static const ProtobufCIntRange galaxy__protocols__overlay_for_peer__show_invitation_dialog__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor galaxy__protocols__overlay_for_peer__show_invitation_dialog__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "galaxy.protocols.overlay_for_peer.ShowInvitationDialog",
  "ShowInvitationDialog",
  "Galaxy__Protocols__OverlayForPeer__ShowInvitationDialog",
  "galaxy.protocols.overlay_for_peer",
  sizeof(Galaxy__Protocols__OverlayForPeer__ShowInvitationDialog),
  1,
  galaxy__protocols__overlay_for_peer__show_invitation_dialog__field_descriptors,
  galaxy__protocols__overlay_for_peer__show_invitation_dialog__field_indices_by_name,
  1,  galaxy__protocols__overlay_for_peer__show_invitation_dialog__number_ranges,
  (ProtobufCMessageInit) galaxy__protocols__overlay_for_peer__show_invitation_dialog__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor galaxy__protocols__overlay_for_peer__game_join_request_notification__field_descriptors[3] =
{
  {
    "inviter_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification, has_inviter_id),
    offsetof(Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification, inviter_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connection_string",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification, connection_string),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification, client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned galaxy__protocols__overlay_for_peer__game_join_request_notification__field_indices_by_name[] = {
  2,   /* field[2] = client_id */
  1,   /* field[1] = connection_string */
  0,   /* field[0] = inviter_id */
};
static const ProtobufCIntRange galaxy__protocols__overlay_for_peer__game_join_request_notification__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor galaxy__protocols__overlay_for_peer__game_join_request_notification__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "galaxy.protocols.overlay_for_peer.GameJoinRequestNotification",
  "GameJoinRequestNotification",
  "Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification",
  "galaxy.protocols.overlay_for_peer",
  sizeof(Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification),
  3,
  galaxy__protocols__overlay_for_peer__game_join_request_notification__field_descriptors,
  galaxy__protocols__overlay_for_peer__game_join_request_notification__field_indices_by_name,
  1,  galaxy__protocols__overlay_for_peer__game_join_request_notification__number_ranges,
  (ProtobufCMessageInit) galaxy__protocols__overlay_for_peer__game_join_request_notification__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor galaxy__protocols__overlay_for_peer__show_web_page__field_descriptors[1] =
{
  {
    "url",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Galaxy__Protocols__OverlayForPeer__ShowWebPage, url),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned galaxy__protocols__overlay_for_peer__show_web_page__field_indices_by_name[] = {
  0,   /* field[0] = url */
};
static const ProtobufCIntRange galaxy__protocols__overlay_for_peer__show_web_page__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor galaxy__protocols__overlay_for_peer__show_web_page__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "galaxy.protocols.overlay_for_peer.ShowWebPage",
  "ShowWebPage",
  "Galaxy__Protocols__OverlayForPeer__ShowWebPage",
  "galaxy.protocols.overlay_for_peer",
  sizeof(Galaxy__Protocols__OverlayForPeer__ShowWebPage),
  1,
  galaxy__protocols__overlay_for_peer__show_web_page__field_descriptors,
  galaxy__protocols__overlay_for_peer__show_web_page__field_indices_by_name,
  1,  galaxy__protocols__overlay_for_peer__show_web_page__number_ranges,
  (ProtobufCMessageInit) galaxy__protocols__overlay_for_peer__show_web_page__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor galaxy__protocols__overlay_for_peer__game_invite_sent_notification__field_descriptors[2] =
{
  {
    "receiver_ids",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification, n_receiver_ids),
    offsetof(Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification, receiver_ids),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connection_string",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification, connection_string),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned galaxy__protocols__overlay_for_peer__game_invite_sent_notification__field_indices_by_name[] = {
  1,   /* field[1] = connection_string */
  0,   /* field[0] = receiver_ids */
};
static const ProtobufCIntRange galaxy__protocols__overlay_for_peer__game_invite_sent_notification__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor galaxy__protocols__overlay_for_peer__game_invite_sent_notification__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "galaxy.protocols.overlay_for_peer.GameInviteSentNotification",
  "GameInviteSentNotification",
  "Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification",
  "galaxy.protocols.overlay_for_peer",
  sizeof(Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification),
  2,
  galaxy__protocols__overlay_for_peer__game_invite_sent_notification__field_descriptors,
  galaxy__protocols__overlay_for_peer__game_invite_sent_notification__field_indices_by_name,
  1,  galaxy__protocols__overlay_for_peer__game_invite_sent_notification__number_ranges,
  (ProtobufCMessageInit) galaxy__protocols__overlay_for_peer__game_invite_sent_notification__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor galaxy__protocols__overlay_for_peer__disable_popups__field_descriptors[1] =
{
  {
    "disabled_popups",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Galaxy__Protocols__OverlayForPeer__DisablePopups, has_disabled_popups),
    offsetof(Galaxy__Protocols__OverlayForPeer__DisablePopups, disabled_popups),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned galaxy__protocols__overlay_for_peer__disable_popups__field_indices_by_name[] = {
  0,   /* field[0] = disabled_popups */
};
static const ProtobufCIntRange galaxy__protocols__overlay_for_peer__disable_popups__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor galaxy__protocols__overlay_for_peer__disable_popups__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "galaxy.protocols.overlay_for_peer.DisablePopups",
  "DisablePopups",
  "Galaxy__Protocols__OverlayForPeer__DisablePopups",
  "galaxy.protocols.overlay_for_peer",
  sizeof(Galaxy__Protocols__OverlayForPeer__DisablePopups),
  1,
  galaxy__protocols__overlay_for_peer__disable_popups__field_descriptors,
  galaxy__protocols__overlay_for_peer__disable_popups__field_indices_by_name,
  1,  galaxy__protocols__overlay_for_peer__disable_popups__number_ranges,
  (ProtobufCMessageInit) galaxy__protocols__overlay_for_peer__disable_popups__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue galaxy__protocols__overlay_for_peer__message_sort__enum_values_by_number[1] =
{
  { "MESSAGE_SORT", "GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__MESSAGE_SORT__MESSAGE_SORT", 6 },
};
static const ProtobufCIntRange galaxy__protocols__overlay_for_peer__message_sort__value_ranges[] = {
{6, 0},{0, 1}
};
static const ProtobufCEnumValueIndex galaxy__protocols__overlay_for_peer__message_sort__enum_values_by_name[1] =
{
  { "MESSAGE_SORT", 0 },
};
const ProtobufCEnumDescriptor galaxy__protocols__overlay_for_peer__message_sort__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "galaxy.protocols.overlay_for_peer.MessageSort",
  "MessageSort",
  "Galaxy__Protocols__OverlayForPeer__MessageSort",
  "galaxy.protocols.overlay_for_peer",
  1,
  galaxy__protocols__overlay_for_peer__message_sort__enum_values_by_number,
  1,
  galaxy__protocols__overlay_for_peer__message_sort__enum_values_by_name,
  1,
  galaxy__protocols__overlay_for_peer__message_sort__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue galaxy__protocols__overlay_for_peer__message_type__enum_values_by_number[7] =
{
  { "UNKNOWN_MESSAGE", "GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__MESSAGE_TYPE__UNKNOWN_MESSAGE", 0 },
  { "STATE_CHANGE_NOTIFICATION", "GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__MESSAGE_TYPE__STATE_CHANGE_NOTIFICATION", 1 },
  { "SHOW_INVITATION_DIALOG", "GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__MESSAGE_TYPE__SHOW_INVITATION_DIALOG", 2 },
  { "GAME_JOIN_REQUEST_NOTIFICATION", "GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__MESSAGE_TYPE__GAME_JOIN_REQUEST_NOTIFICATION", 3 },
  { "SHOW_WEB_PAGE", "GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__MESSAGE_TYPE__SHOW_WEB_PAGE", 4 },
  { "GAME_INVITE_SENT_NOTIFICATION", "GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__MESSAGE_TYPE__GAME_INVITE_SENT_NOTIFICATION", 5 },
  { "OVERLAY_INITIALIZED_NOTIFICATION", "GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__MESSAGE_TYPE__OVERLAY_INITIALIZED_NOTIFICATION", 6 },
};
static const ProtobufCIntRange galaxy__protocols__overlay_for_peer__message_type__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex galaxy__protocols__overlay_for_peer__message_type__enum_values_by_name[9] =
{
  { "DISABLE_POPUPS", 6 },
  { "GAME_INVITE_SENT_NOTIFICATION", 5 },
  { "GAME_JOIN_REQUEST_NOTIFICATION", 3 },
  { "OVERLAY_INITIALIZED_NOTIFICATION", 6 },
  { "SHOW_INVITATION_DIALOG", 2 },
  { "SHOW_WEB_PAGE", 4 },
  { "STATE_CHANGE_NOTIFICATION", 1 },
  { "UNKNOWN_MESSAGE", 0 },
  { "VISIBILITY_CHANGE_NOTIFICATION", 1 },
};
const ProtobufCEnumDescriptor galaxy__protocols__overlay_for_peer__message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "galaxy.protocols.overlay_for_peer.MessageType",
  "MessageType",
  "Galaxy__Protocols__OverlayForPeer__MessageType",
  "galaxy.protocols.overlay_for_peer",
  7,
  galaxy__protocols__overlay_for_peer__message_type__enum_values_by_number,
  9,
  galaxy__protocols__overlay_for_peer__message_type__enum_values_by_name,
  1,
  galaxy__protocols__overlay_for_peer__message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
