/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: galaxy.protocols.overlay_for_peer.proto */

#ifndef PROTOBUF_C_galaxy_2eprotocols_2eoverlay_5ffor_5fpeer_2eproto__INCLUDED
#define PROTOBUF_C_galaxy_2eprotocols_2eoverlay_5ffor_5fpeer_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Galaxy__Protocols__OverlayForPeer__StateChangeNotification Galaxy__Protocols__OverlayForPeer__StateChangeNotification;
typedef struct Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification;
typedef struct Galaxy__Protocols__OverlayForPeer__ShowInvitationDialog Galaxy__Protocols__OverlayForPeer__ShowInvitationDialog;
typedef struct Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification;
typedef struct Galaxy__Protocols__OverlayForPeer__ShowWebPage Galaxy__Protocols__OverlayForPeer__ShowWebPage;
typedef struct Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification;
typedef struct Galaxy__Protocols__OverlayForPeer__DisablePopups Galaxy__Protocols__OverlayForPeer__DisablePopups;


/* --- enums --- */

typedef enum _Galaxy__Protocols__OverlayForPeer__MessageSort {
  GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__MESSAGE_SORT__MESSAGE_SORT = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__MESSAGE_SORT)
} Galaxy__Protocols__OverlayForPeer__MessageSort;
typedef enum _Galaxy__Protocols__OverlayForPeer__MessageType {
  GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__MESSAGE_TYPE__UNKNOWN_MESSAGE = 0,
  GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__MESSAGE_TYPE__STATE_CHANGE_NOTIFICATION = 1,
  GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__MESSAGE_TYPE__VISIBILITY_CHANGE_NOTIFICATION = 1,
  GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__MESSAGE_TYPE__SHOW_INVITATION_DIALOG = 2,
  GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__MESSAGE_TYPE__GAME_JOIN_REQUEST_NOTIFICATION = 3,
  GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__MESSAGE_TYPE__SHOW_WEB_PAGE = 4,
  GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__MESSAGE_TYPE__GAME_INVITE_SENT_NOTIFICATION = 5,
  GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__MESSAGE_TYPE__OVERLAY_INITIALIZED_NOTIFICATION = 6,
  GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__MESSAGE_TYPE__DISABLE_POPUPS = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__MESSAGE_TYPE)
} Galaxy__Protocols__OverlayForPeer__MessageType;

/* --- messages --- */

struct  Galaxy__Protocols__OverlayForPeer__StateChangeNotification
{
  ProtobufCMessage base;
  protobuf_c_boolean has_active;
  protobuf_c_boolean active;
};
#define GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__STATE_CHANGE_NOTIFICATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&galaxy__protocols__overlay_for_peer__state_change_notification__descriptor) \
, 0, 0 }


struct  Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification
{
  ProtobufCMessage base;
  protobuf_c_boolean has_visible;
  protobuf_c_boolean visible;
};
#define GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__VISIBILITY_CHANGE_NOTIFICATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&galaxy__protocols__overlay_for_peer__visibility_change_notification__descriptor) \
, 0, 0 }


struct  Galaxy__Protocols__OverlayForPeer__ShowInvitationDialog
{
  ProtobufCMessage base;
  char *connection_string;
};
#define GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__SHOW_INVITATION_DIALOG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&galaxy__protocols__overlay_for_peer__show_invitation_dialog__descriptor) \
, NULL }


struct  Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification
{
  ProtobufCMessage base;
  protobuf_c_boolean has_inviter_id;
  uint64_t inviter_id;
  char *connection_string;
  char *client_id;
};
#define GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__GAME_JOIN_REQUEST_NOTIFICATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&galaxy__protocols__overlay_for_peer__game_join_request_notification__descriptor) \
, 0, 0, NULL, NULL }


struct  Galaxy__Protocols__OverlayForPeer__ShowWebPage
{
  ProtobufCMessage base;
  char *url;
};
#define GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__SHOW_WEB_PAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&galaxy__protocols__overlay_for_peer__show_web_page__descriptor) \
, NULL }


struct  Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification
{
  ProtobufCMessage base;
  size_t n_receiver_ids;
  uint64_t *receiver_ids;
  char *connection_string;
};
#define GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__GAME_INVITE_SENT_NOTIFICATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&galaxy__protocols__overlay_for_peer__game_invite_sent_notification__descriptor) \
, 0,NULL, NULL }


struct  Galaxy__Protocols__OverlayForPeer__DisablePopups
{
  ProtobufCMessage base;
  protobuf_c_boolean has_disabled_popups;
  protobuf_c_boolean disabled_popups;
};
#define GALAXY__PROTOCOLS__OVERLAY_FOR_PEER__DISABLE_POPUPS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&galaxy__protocols__overlay_for_peer__disable_popups__descriptor) \
, 0, 0 }


/* Galaxy__Protocols__OverlayForPeer__StateChangeNotification methods */
void   galaxy__protocols__overlay_for_peer__state_change_notification__init
                     (Galaxy__Protocols__OverlayForPeer__StateChangeNotification         *message);
size_t galaxy__protocols__overlay_for_peer__state_change_notification__get_packed_size
                     (const Galaxy__Protocols__OverlayForPeer__StateChangeNotification   *message);
size_t galaxy__protocols__overlay_for_peer__state_change_notification__pack
                     (const Galaxy__Protocols__OverlayForPeer__StateChangeNotification   *message,
                      uint8_t             *out);
size_t galaxy__protocols__overlay_for_peer__state_change_notification__pack_to_buffer
                     (const Galaxy__Protocols__OverlayForPeer__StateChangeNotification   *message,
                      ProtobufCBuffer     *buffer);
Galaxy__Protocols__OverlayForPeer__StateChangeNotification *
       galaxy__protocols__overlay_for_peer__state_change_notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   galaxy__protocols__overlay_for_peer__state_change_notification__free_unpacked
                     (Galaxy__Protocols__OverlayForPeer__StateChangeNotification *message,
                      ProtobufCAllocator *allocator);
/* Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification methods */
void   galaxy__protocols__overlay_for_peer__visibility_change_notification__init
                     (Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification         *message);
size_t galaxy__protocols__overlay_for_peer__visibility_change_notification__get_packed_size
                     (const Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification   *message);
size_t galaxy__protocols__overlay_for_peer__visibility_change_notification__pack
                     (const Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification   *message,
                      uint8_t             *out);
size_t galaxy__protocols__overlay_for_peer__visibility_change_notification__pack_to_buffer
                     (const Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification   *message,
                      ProtobufCBuffer     *buffer);
Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification *
       galaxy__protocols__overlay_for_peer__visibility_change_notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   galaxy__protocols__overlay_for_peer__visibility_change_notification__free_unpacked
                     (Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification *message,
                      ProtobufCAllocator *allocator);
/* Galaxy__Protocols__OverlayForPeer__ShowInvitationDialog methods */
void   galaxy__protocols__overlay_for_peer__show_invitation_dialog__init
                     (Galaxy__Protocols__OverlayForPeer__ShowInvitationDialog         *message);
size_t galaxy__protocols__overlay_for_peer__show_invitation_dialog__get_packed_size
                     (const Galaxy__Protocols__OverlayForPeer__ShowInvitationDialog   *message);
size_t galaxy__protocols__overlay_for_peer__show_invitation_dialog__pack
                     (const Galaxy__Protocols__OverlayForPeer__ShowInvitationDialog   *message,
                      uint8_t             *out);
size_t galaxy__protocols__overlay_for_peer__show_invitation_dialog__pack_to_buffer
                     (const Galaxy__Protocols__OverlayForPeer__ShowInvitationDialog   *message,
                      ProtobufCBuffer     *buffer);
Galaxy__Protocols__OverlayForPeer__ShowInvitationDialog *
       galaxy__protocols__overlay_for_peer__show_invitation_dialog__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   galaxy__protocols__overlay_for_peer__show_invitation_dialog__free_unpacked
                     (Galaxy__Protocols__OverlayForPeer__ShowInvitationDialog *message,
                      ProtobufCAllocator *allocator);
/* Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification methods */
void   galaxy__protocols__overlay_for_peer__game_join_request_notification__init
                     (Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification         *message);
size_t galaxy__protocols__overlay_for_peer__game_join_request_notification__get_packed_size
                     (const Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification   *message);
size_t galaxy__protocols__overlay_for_peer__game_join_request_notification__pack
                     (const Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification   *message,
                      uint8_t             *out);
size_t galaxy__protocols__overlay_for_peer__game_join_request_notification__pack_to_buffer
                     (const Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification   *message,
                      ProtobufCBuffer     *buffer);
Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification *
       galaxy__protocols__overlay_for_peer__game_join_request_notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   galaxy__protocols__overlay_for_peer__game_join_request_notification__free_unpacked
                     (Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification *message,
                      ProtobufCAllocator *allocator);
/* Galaxy__Protocols__OverlayForPeer__ShowWebPage methods */
void   galaxy__protocols__overlay_for_peer__show_web_page__init
                     (Galaxy__Protocols__OverlayForPeer__ShowWebPage         *message);
size_t galaxy__protocols__overlay_for_peer__show_web_page__get_packed_size
                     (const Galaxy__Protocols__OverlayForPeer__ShowWebPage   *message);
size_t galaxy__protocols__overlay_for_peer__show_web_page__pack
                     (const Galaxy__Protocols__OverlayForPeer__ShowWebPage   *message,
                      uint8_t             *out);
size_t galaxy__protocols__overlay_for_peer__show_web_page__pack_to_buffer
                     (const Galaxy__Protocols__OverlayForPeer__ShowWebPage   *message,
                      ProtobufCBuffer     *buffer);
Galaxy__Protocols__OverlayForPeer__ShowWebPage *
       galaxy__protocols__overlay_for_peer__show_web_page__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   galaxy__protocols__overlay_for_peer__show_web_page__free_unpacked
                     (Galaxy__Protocols__OverlayForPeer__ShowWebPage *message,
                      ProtobufCAllocator *allocator);
/* Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification methods */
void   galaxy__protocols__overlay_for_peer__game_invite_sent_notification__init
                     (Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification         *message);
size_t galaxy__protocols__overlay_for_peer__game_invite_sent_notification__get_packed_size
                     (const Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification   *message);
size_t galaxy__protocols__overlay_for_peer__game_invite_sent_notification__pack
                     (const Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification   *message,
                      uint8_t             *out);
size_t galaxy__protocols__overlay_for_peer__game_invite_sent_notification__pack_to_buffer
                     (const Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification   *message,
                      ProtobufCBuffer     *buffer);
Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification *
       galaxy__protocols__overlay_for_peer__game_invite_sent_notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   galaxy__protocols__overlay_for_peer__game_invite_sent_notification__free_unpacked
                     (Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification *message,
                      ProtobufCAllocator *allocator);
/* Galaxy__Protocols__OverlayForPeer__DisablePopups methods */
void   galaxy__protocols__overlay_for_peer__disable_popups__init
                     (Galaxy__Protocols__OverlayForPeer__DisablePopups         *message);
size_t galaxy__protocols__overlay_for_peer__disable_popups__get_packed_size
                     (const Galaxy__Protocols__OverlayForPeer__DisablePopups   *message);
size_t galaxy__protocols__overlay_for_peer__disable_popups__pack
                     (const Galaxy__Protocols__OverlayForPeer__DisablePopups   *message,
                      uint8_t             *out);
size_t galaxy__protocols__overlay_for_peer__disable_popups__pack_to_buffer
                     (const Galaxy__Protocols__OverlayForPeer__DisablePopups   *message,
                      ProtobufCBuffer     *buffer);
Galaxy__Protocols__OverlayForPeer__DisablePopups *
       galaxy__protocols__overlay_for_peer__disable_popups__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   galaxy__protocols__overlay_for_peer__disable_popups__free_unpacked
                     (Galaxy__Protocols__OverlayForPeer__DisablePopups *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Galaxy__Protocols__OverlayForPeer__StateChangeNotification_Closure)
                 (const Galaxy__Protocols__OverlayForPeer__StateChangeNotification *message,
                  void *closure_data);
typedef void (*Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification_Closure)
                 (const Galaxy__Protocols__OverlayForPeer__VisibilityChangeNotification *message,
                  void *closure_data);
typedef void (*Galaxy__Protocols__OverlayForPeer__ShowInvitationDialog_Closure)
                 (const Galaxy__Protocols__OverlayForPeer__ShowInvitationDialog *message,
                  void *closure_data);
typedef void (*Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification_Closure)
                 (const Galaxy__Protocols__OverlayForPeer__GameJoinRequestNotification *message,
                  void *closure_data);
typedef void (*Galaxy__Protocols__OverlayForPeer__ShowWebPage_Closure)
                 (const Galaxy__Protocols__OverlayForPeer__ShowWebPage *message,
                  void *closure_data);
typedef void (*Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification_Closure)
                 (const Galaxy__Protocols__OverlayForPeer__GameInviteSentNotification *message,
                  void *closure_data);
typedef void (*Galaxy__Protocols__OverlayForPeer__DisablePopups_Closure)
                 (const Galaxy__Protocols__OverlayForPeer__DisablePopups *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    galaxy__protocols__overlay_for_peer__message_sort__descriptor;
extern const ProtobufCEnumDescriptor    galaxy__protocols__overlay_for_peer__message_type__descriptor;
extern const ProtobufCMessageDescriptor galaxy__protocols__overlay_for_peer__state_change_notification__descriptor;
extern const ProtobufCMessageDescriptor galaxy__protocols__overlay_for_peer__visibility_change_notification__descriptor;
extern const ProtobufCMessageDescriptor galaxy__protocols__overlay_for_peer__show_invitation_dialog__descriptor;
extern const ProtobufCMessageDescriptor galaxy__protocols__overlay_for_peer__game_join_request_notification__descriptor;
extern const ProtobufCMessageDescriptor galaxy__protocols__overlay_for_peer__show_web_page__descriptor;
extern const ProtobufCMessageDescriptor galaxy__protocols__overlay_for_peer__game_invite_sent_notification__descriptor;
extern const ProtobufCMessageDescriptor galaxy__protocols__overlay_for_peer__disable_popups__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_galaxy_2eprotocols_2eoverlay_5ffor_5fpeer_2eproto__INCLUDED */
