/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: galaxy.common.protocols.connection.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "galaxy.common.protocols.connection.pb-c.h"
void   galaxy__common__protocols__connection__ping__init
                     (Galaxy__Common__Protocols__Connection__Ping         *message)
{
  static const Galaxy__Common__Protocols__Connection__Ping init_value = GALAXY__COMMON__PROTOCOLS__CONNECTION__PING__INIT;
  *message = init_value;
}
size_t galaxy__common__protocols__connection__ping__get_packed_size
                     (const Galaxy__Common__Protocols__Connection__Ping *message)
{
  assert(message->base.descriptor == &galaxy__common__protocols__connection__ping__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t galaxy__common__protocols__connection__ping__pack
                     (const Galaxy__Common__Protocols__Connection__Ping *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &galaxy__common__protocols__connection__ping__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t galaxy__common__protocols__connection__ping__pack_to_buffer
                     (const Galaxy__Common__Protocols__Connection__Ping *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &galaxy__common__protocols__connection__ping__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Galaxy__Common__Protocols__Connection__Ping *
       galaxy__common__protocols__connection__ping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Galaxy__Common__Protocols__Connection__Ping *)
     protobuf_c_message_unpack (&galaxy__common__protocols__connection__ping__descriptor,
                                allocator, len, data);
}
void   galaxy__common__protocols__connection__ping__free_unpacked
                     (Galaxy__Common__Protocols__Connection__Ping *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &galaxy__common__protocols__connection__ping__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   galaxy__common__protocols__connection__pong__init
                     (Galaxy__Common__Protocols__Connection__Pong         *message)
{
  static const Galaxy__Common__Protocols__Connection__Pong init_value = GALAXY__COMMON__PROTOCOLS__CONNECTION__PONG__INIT;
  *message = init_value;
}
size_t galaxy__common__protocols__connection__pong__get_packed_size
                     (const Galaxy__Common__Protocols__Connection__Pong *message)
{
  assert(message->base.descriptor == &galaxy__common__protocols__connection__pong__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t galaxy__common__protocols__connection__pong__pack
                     (const Galaxy__Common__Protocols__Connection__Pong *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &galaxy__common__protocols__connection__pong__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t galaxy__common__protocols__connection__pong__pack_to_buffer
                     (const Galaxy__Common__Protocols__Connection__Pong *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &galaxy__common__protocols__connection__pong__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Galaxy__Common__Protocols__Connection__Pong *
       galaxy__common__protocols__connection__pong__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Galaxy__Common__Protocols__Connection__Pong *)
     protobuf_c_message_unpack (&galaxy__common__protocols__connection__pong__descriptor,
                                allocator, len, data);
}
void   galaxy__common__protocols__connection__pong__free_unpacked
                     (Galaxy__Common__Protocols__Connection__Pong *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &galaxy__common__protocols__connection__pong__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor galaxy__common__protocols__connection__ping__field_descriptors[1] =
{
  {
    "ping_time",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Galaxy__Common__Protocols__Connection__Ping, has_ping_time),
    offsetof(Galaxy__Common__Protocols__Connection__Ping, ping_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned galaxy__common__protocols__connection__ping__field_indices_by_name[] = {
  0,   /* field[0] = ping_time */
};
static const ProtobufCIntRange galaxy__common__protocols__connection__ping__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor galaxy__common__protocols__connection__ping__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "galaxy.common.protocols.connection.Ping",
  "Ping",
  "Galaxy__Common__Protocols__Connection__Ping",
  "galaxy.common.protocols.connection",
  sizeof(Galaxy__Common__Protocols__Connection__Ping),
  1,
  galaxy__common__protocols__connection__ping__field_descriptors,
  galaxy__common__protocols__connection__ping__field_indices_by_name,
  1,  galaxy__common__protocols__connection__ping__number_ranges,
  (ProtobufCMessageInit) galaxy__common__protocols__connection__ping__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor galaxy__common__protocols__connection__pong__field_descriptors[1] =
{
  {
    "ping_time",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Galaxy__Common__Protocols__Connection__Pong, has_ping_time),
    offsetof(Galaxy__Common__Protocols__Connection__Pong, ping_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned galaxy__common__protocols__connection__pong__field_indices_by_name[] = {
  0,   /* field[0] = ping_time */
};
static const ProtobufCIntRange galaxy__common__protocols__connection__pong__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor galaxy__common__protocols__connection__pong__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "galaxy.common.protocols.connection.Pong",
  "Pong",
  "Galaxy__Common__Protocols__Connection__Pong",
  "galaxy.common.protocols.connection",
  sizeof(Galaxy__Common__Protocols__Connection__Pong),
  1,
  galaxy__common__protocols__connection__pong__field_descriptors,
  galaxy__common__protocols__connection__pong__field_indices_by_name,
  1,  galaxy__common__protocols__connection__pong__number_ranges,
  (ProtobufCMessageInit) galaxy__common__protocols__connection__pong__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue galaxy__common__protocols__connection__message_type__enum_values_by_number[3] =
{
  { "UNKNOWN_MESSAGE", "GALAXY__COMMON__PROTOCOLS__CONNECTION__MESSAGE_TYPE__UNKNOWN_MESSAGE", 0 },
  { "PING", "GALAXY__COMMON__PROTOCOLS__CONNECTION__MESSAGE_TYPE__PING", 1 },
  { "PONG", "GALAXY__COMMON__PROTOCOLS__CONNECTION__MESSAGE_TYPE__PONG", 2 },
};
static const ProtobufCIntRange galaxy__common__protocols__connection__message_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex galaxy__common__protocols__connection__message_type__enum_values_by_name[3] =
{
  { "PING", 1 },
  { "PONG", 2 },
  { "UNKNOWN_MESSAGE", 0 },
};
const ProtobufCEnumDescriptor galaxy__common__protocols__connection__message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "galaxy.common.protocols.connection.MessageType",
  "MessageType",
  "Galaxy__Common__Protocols__Connection__MessageType",
  "galaxy.common.protocols.connection",
  3,
  galaxy__common__protocols__connection__message_type__enum_values_by_number,
  3,
  galaxy__common__protocols__connection__message_type__enum_values_by_name,
  1,
  galaxy__common__protocols__connection__message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
