/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gog.protocols.pb.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gog.protocols.pb.pb-c.h"
void   gog__protocols__pb__header__init
                     (Gog__Protocols__Pb__Header         *message)
{
  static const Gog__Protocols__Pb__Header init_value = GOG__PROTOCOLS__PB__HEADER__INIT;
  *message = init_value;
}
size_t gog__protocols__pb__header__get_packed_size
                     (const Gog__Protocols__Pb__Header *message)
{
  assert(message->base.descriptor == &gog__protocols__pb__header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gog__protocols__pb__header__pack
                     (const Gog__Protocols__Pb__Header *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gog__protocols__pb__header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gog__protocols__pb__header__pack_to_buffer
                     (const Gog__Protocols__Pb__Header *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gog__protocols__pb__header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gog__Protocols__Pb__Header *
       gog__protocols__pb__header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gog__Protocols__Pb__Header *)
     protobuf_c_message_unpack (&gog__protocols__pb__header__descriptor,
                                allocator, len, data);
}
void   gog__protocols__pb__header__free_unpacked
                     (Gog__Protocols__Pb__Header *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gog__protocols__pb__header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gog__protocols__pb__response__init
                     (Gog__Protocols__Pb__Response         *message)
{
  static const Gog__Protocols__Pb__Response init_value = GOG__PROTOCOLS__PB__RESPONSE__INIT;
  *message = init_value;
}
size_t gog__protocols__pb__response__get_packed_size
                     (const Gog__Protocols__Pb__Response *message)
{
  assert(message->base.descriptor == &gog__protocols__pb__response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gog__protocols__pb__response__pack
                     (const Gog__Protocols__Pb__Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gog__protocols__pb__response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gog__protocols__pb__response__pack_to_buffer
                     (const Gog__Protocols__Pb__Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gog__protocols__pb__response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gog__Protocols__Pb__Response *
       gog__protocols__pb__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gog__Protocols__Pb__Response *)
     protobuf_c_message_unpack (&gog__protocols__pb__response__descriptor,
                                allocator, len, data);
}
void   gog__protocols__pb__response__free_unpacked
                     (Gog__Protocols__Pb__Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gog__protocols__pb__response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const uint32_t gog__protocols__pb__header__size__default_value = 0u;
static const ProtobufCFieldDescriptor gog__protocols__pb__header__field_descriptors[4] =
{
  {
    "sort",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gog__Protocols__Pb__Header, sort),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Gog__Protocols__Pb__Header, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Gog__Protocols__Pb__Header, has_size),
    offsetof(Gog__Protocols__Pb__Header, size),
    NULL,
    &gog__protocols__pb__header__size__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "oseq",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Gog__Protocols__Pb__Header, has_oseq),
    offsetof(Gog__Protocols__Pb__Header, oseq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gog__protocols__pb__header__field_indices_by_name[] = {
  3,   /* field[3] = oseq */
  2,   /* field[2] = size */
  0,   /* field[0] = sort */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange gog__protocols__pb__header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor gog__protocols__pb__header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gog.protocols.pb.Header",
  "Header",
  "Gog__Protocols__Pb__Header",
  "gog.protocols.pb",
  sizeof(Gog__Protocols__Pb__Header),
  4,
  gog__protocols__pb__header__field_descriptors,
  gog__protocols__pb__header__field_indices_by_name,
  1,  gog__protocols__pb__header__number_ranges,
  (ProtobufCMessageInit) gog__protocols__pb__header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue gog__protocols__pb__response__status__enum_values_by_number[11] =
{
  { "UNKNOWN_RESPONSE", "GOG__PROTOCOLS__PB__RESPONSE__STATUS__UNKNOWN_RESPONSE", 0 },
  { "OK", "GOG__PROTOCOLS__PB__RESPONSE__STATUS__OK", 200 },
  { "ACCEPTED", "GOG__PROTOCOLS__PB__RESPONSE__STATUS__ACCEPTED", 202 },
  { "BAD_REQUEST", "GOG__PROTOCOLS__PB__RESPONSE__STATUS__BAD_REQUEST", 400 },
  { "UNAUTHORIZED", "GOG__PROTOCOLS__PB__RESPONSE__STATUS__UNAUTHORIZED", 401 },
  { "FORBIDDEN", "GOG__PROTOCOLS__PB__RESPONSE__STATUS__FORBIDDEN", 403 },
  { "NOT_FOUND", "GOG__PROTOCOLS__PB__RESPONSE__STATUS__NOT_FOUND", 404 },
  { "CONFLICT", "GOG__PROTOCOLS__PB__RESPONSE__STATUS__CONFLICT", 409 },
  { "INTERNAL_ERROR", "GOG__PROTOCOLS__PB__RESPONSE__STATUS__INTERNAL_ERROR", 500 },
  { "NOT_IMPLEMENTED", "GOG__PROTOCOLS__PB__RESPONSE__STATUS__NOT_IMPLEMENTED", 501 },
  { "UNAVAILABLE", "GOG__PROTOCOLS__PB__RESPONSE__STATUS__UNAVAILABLE", 503 },
};
static const ProtobufCIntRange gog__protocols__pb__response__status__value_ranges[] = {
{0, 0},{200, 1},{202, 2},{400, 3},{403, 5},{409, 7},{500, 8},{503, 10},{0, 11}
};
static const ProtobufCEnumValueIndex gog__protocols__pb__response__status__enum_values_by_name[11] =
{
  { "ACCEPTED", 2 },
  { "BAD_REQUEST", 3 },
  { "CONFLICT", 7 },
  { "FORBIDDEN", 5 },
  { "INTERNAL_ERROR", 8 },
  { "NOT_FOUND", 6 },
  { "NOT_IMPLEMENTED", 9 },
  { "OK", 1 },
  { "UNAUTHORIZED", 4 },
  { "UNAVAILABLE", 10 },
  { "UNKNOWN_RESPONSE", 0 },
};
const ProtobufCEnumDescriptor gog__protocols__pb__response__status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "gog.protocols.pb.Response.Status",
  "Status",
  "Gog__Protocols__Pb__Response__Status",
  "gog.protocols.pb",
  11,
  gog__protocols__pb__response__status__enum_values_by_number,
  11,
  gog__protocols__pb__response__status__enum_values_by_name,
  8,
  gog__protocols__pb__response__status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
#define gog__protocols__pb__response__field_descriptors NULL
#define gog__protocols__pb__response__field_indices_by_name NULL
#define gog__protocols__pb__response__number_ranges NULL
const ProtobufCMessageDescriptor gog__protocols__pb__response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gog.protocols.pb.Response",
  "Response",
  "Gog__Protocols__Pb__Response",
  "gog.protocols.pb",
  sizeof(Gog__Protocols__Pb__Response),
  0,
  gog__protocols__pb__response__field_descriptors,
  gog__protocols__pb__response__field_indices_by_name,
  0,  gog__protocols__pb__response__number_ranges,
  (ProtobufCMessageInit) gog__protocols__pb__response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
